theme: minima
title: MITRE Cyber Analytics Repository
author: The MITRE Corporation
contributing: https://github.com/mitre-attack/car/blob/master/CONTRIBUTING.md
license_url: https://github.com/mitre-attack/car/blob/master/LICENSE.txt
privacy_policy_url: https://car.mitre.org/privacy_policy
terms_of_use_url: https://attack.mitre.org/resources/terms-of-use/
